// This file is auto-generated by @hey-api/openapi-ts

export const AgentPointCreateSchema = {
    properties: {
        created_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created Time'
        },
        location_id: {
            type: 'integer',
            title: 'Location Id'
        }
    },
    type: 'object',
    required: ['location_id'],
    title: 'AgentPointCreate'
} as const;

export const AgentPointEventCreateSchema = {
    properties: {
        event_time: {
            type: 'string',
            format: 'date-time',
            title: 'Event Time'
        },
        event_type: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Event Type'
        },
        metric_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Name'
        },
        metric_delta: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Delta'
        },
        metric_value_num: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Value Num'
        },
        metric_value_bool: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Value Bool'
        },
        agent_point_id: {
            type: 'integer',
            title: 'Agent Point Id'
        }
    },
    type: 'object',
    required: ['event_time', 'event_type', 'agent_point_id'],
    title: 'AgentPointEventCreate'
} as const;

export const AgentPointEventPublicSchema = {
    properties: {
        event_time: {
            type: 'string',
            format: 'date-time',
            title: 'Event Time'
        },
        event_type: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Event Type'
        },
        metric_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Name'
        },
        metric_delta: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Delta'
        },
        metric_value_num: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Value Num'
        },
        metric_value_bool: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Value Bool'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        agent_point_id: {
            type: 'integer',
            title: 'Agent Point Id'
        }
    },
    type: 'object',
    required: ['event_time', 'event_type', 'id', 'agent_point_id'],
    title: 'AgentPointEventPublic'
} as const;

export const AgentPointEventUpdateSchema = {
    properties: {
        event_time: {
            type: 'string',
            format: 'date-time',
            title: 'Event Time'
        },
        event_type: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Event Type'
        },
        metric_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Name'
        },
        metric_delta: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Delta'
        },
        metric_value_num: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Value Num'
        },
        metric_value_bool: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric Value Bool'
        },
        agent_point_id: {
            type: 'integer',
            title: 'Agent Point Id'
        }
    },
    type: 'object',
    required: ['event_time', 'event_type', 'agent_point_id'],
    title: 'AgentPointEventUpdate'
} as const;

export const AgentPointEventsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AgentPointEventPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AgentPointEventsPublic'
} as const;

export const AgentPointPublicSchema = {
    properties: {
        created_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created Time'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        location: {
            '$ref': '#/components/schemas/LocationPublic'
        }
    },
    type: 'object',
    required: ['id', 'location'],
    title: 'AgentPointPublic'
} as const;

export const AgentPointUpdateSchema = {
    properties: {
        created_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created Time'
        },
        location_id: {
            type: 'integer',
            title: 'Location Id'
        }
    },
    type: 'object',
    required: ['location_id'],
    title: 'AgentPointUpdate'
} as const;

export const AgentPointsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AgentPointPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AgentPointsPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const EmployeeCreateSchema = {
    properties: {
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        grade_id: {
            type: 'integer',
            title: 'Grade Id'
        },
        start_location_id: {
            type: 'integer',
            title: 'Start Location Id'
        }
    },
    type: 'object',
    required: ['user_id', 'grade_id', 'start_location_id'],
    title: 'EmployeeCreate'
} as const;

export const EmployeePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        grade_id: {
            type: 'integer',
            title: 'Grade Id'
        },
        start_location_id: {
            type: 'integer',
            title: 'Start Location Id'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'grade_id', 'start_location_id'],
    title: 'EmployeePublic'
} as const;

export const EmployeeUpdateSchema = {
    properties: {
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        grade_id: {
            type: 'integer',
            title: 'Grade Id'
        },
        start_location_id: {
            type: 'integer',
            title: 'Start Location Id'
        }
    },
    type: 'object',
    required: ['user_id', 'grade_id', 'start_location_id'],
    title: 'EmployeeUpdate'
} as const;

export const EmployeesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/EmployeePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'EmployeesPublic'
} as const;

export const GradeCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name'
        },
        level: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Level'
        }
    },
    type: 'object',
    required: ['name', 'level'],
    title: 'GradeCreate'
} as const;

export const GradePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name'
        },
        level: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Level'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'level', 'id'],
    title: 'GradePublic'
} as const;

export const GradeUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name'
        },
        level: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Level'
        }
    },
    type: 'object',
    required: ['name', 'level'],
    title: 'GradeUpdate'
} as const;

export const GradesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GradePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GradesPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LocationCreateSchema = {
    properties: {
        address: {
            type: 'string',
            maxLength: 255,
            title: 'Address'
        },
        lat: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 90,
                    minimum: -90
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lat'
        },
        lon: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 180,
                    minimum: -180
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lon'
        }
    },
    type: 'object',
    required: ['address'],
    title: 'LocationCreate'
} as const;

export const LocationPublicSchema = {
    properties: {
        address: {
            type: 'string',
            maxLength: 255,
            title: 'Address'
        },
        lat: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 90,
                    minimum: -90
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lat'
        },
        lon: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 180,
                    minimum: -180
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lon'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['address', 'id'],
    title: 'LocationPublic'
} as const;

export const LocationUpdateSchema = {
    properties: {
        address: {
            type: 'string',
            maxLength: 255,
            title: 'Address'
        },
        lat: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 90,
                    minimum: -90
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lat'
        },
        lon: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 180,
                    minimum: -180
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lon'
        }
    },
    type: 'object',
    required: ['address'],
    title: 'LocationUpdate'
} as const;

export const LocationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LocationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LocationsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const PrioritiesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PriorityPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PrioritiesPublic'
} as const;

export const PriorityCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 32,
            title: 'Name'
        },
        level: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Level'
        }
    },
    type: 'object',
    required: ['name', 'level'],
    title: 'PriorityCreate'
} as const;

export const PriorityPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 32,
            title: 'Name'
        },
        level: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Level'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'level', 'id'],
    title: 'PriorityPublic'
} as const;

export const PriorityUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 32,
            title: 'Name'
        },
        level: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Level'
        }
    },
    type: 'object',
    required: ['name', 'level'],
    title: 'PriorityUpdate'
} as const;

export const RoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoleCreate'
} as const;

export const RolePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'RolePublic'
} as const;

export const RoleUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoleUpdate'
} as const;

export const RolesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RolePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RolesPublic'
} as const;

export const TaskAgentPointManagerConfirmUpdateSchema = {
    properties: {
        confirmed: {
            type: 'boolean',
            title: 'Confirmed'
        },
        comment: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4096
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        }
    },
    type: 'object',
    required: ['confirmed'],
    title: 'TaskAgentPointManagerConfirmUpdate',
    description: 'Решение менеджера агентской точки по выполненной задаче.'
} as const;

export const TaskCompleteUpdateSchema = {
    properties: {
        comment: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4096
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        }
    },
    type: 'object',
    title: 'TaskCompleteUpdate',
    description: 'Отметка задачи как выполненной с опциональным комментарием.'
} as const;

export const TaskCreateSchema = {
    properties: {
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        finish_time: {
            type: 'string',
            format: 'date-time',
            title: 'Finish Time'
        },
        comment: {
            type: 'string',
            maxLength: 4096,
            title: 'Comment'
        },
        employee_id: {
            type: 'integer',
            title: 'Employee Id'
        },
        task_type_id: {
            type: 'integer',
            title: 'Task Type Id'
        },
        agent_point_id: {
            type: 'integer',
            title: 'Agent Point Id'
        },
        task_status_id: {
            type: 'integer',
            title: 'Task Status Id'
        }
    },
    type: 'object',
    required: ['start_time', 'finish_time', 'comment', 'employee_id', 'task_type_id', 'agent_point_id', 'task_status_id'],
    title: 'TaskCreate'
} as const;

export const TaskMePublicSchema = {
    properties: {
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        finish_time: {
            type: 'string',
            format: 'date-time',
            title: 'Finish Time'
        },
        comment: {
            type: 'string',
            maxLength: 4096,
            title: 'Comment'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        agent_point: {
            '$ref': '#/components/schemas/AgentPointPublic'
        }
    },
    type: 'object',
    required: ['start_time', 'finish_time', 'comment', 'id', 'agent_point'],
    title: 'TaskMePublic'
} as const;

export const TaskPublicSchema = {
    properties: {
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        finish_time: {
            type: 'string',
            format: 'date-time',
            title: 'Finish Time'
        },
        comment: {
            type: 'string',
            maxLength: 4096,
            title: 'Comment'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        employee_id: {
            type: 'integer',
            title: 'Employee Id'
        },
        task_type_id: {
            type: 'integer',
            title: 'Task Type Id'
        },
        agent_point_id: {
            type: 'integer',
            title: 'Agent Point Id'
        },
        task_status_id: {
            type: 'integer',
            title: 'Task Status Id'
        }
    },
    type: 'object',
    required: ['start_time', 'finish_time', 'comment', 'id', 'employee_id', 'task_type_id', 'agent_point_id', 'task_status_id'],
    title: 'TaskPublic'
} as const;

export const TaskSelfUpdateSchema = {
    properties: {
        task_status_id: {
            type: 'integer',
            title: 'Task Status Id'
        },
        comment: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4096
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        }
    },
    type: 'object',
    required: ['task_status_id'],
    title: 'TaskSelfUpdate',
    description: 'Обновление статуса и комментария выездным сотрудником к своей задаче.'
} as const;

export const TaskSkipUpdateSchema = {
    properties: {
        comment: {
            type: 'string',
            maxLength: 4096,
            minLength: 1,
            title: 'Comment'
        }
    },
    type: 'object',
    required: ['comment'],
    title: 'TaskSkipUpdate',
    description: 'Пропуск задачи с обязательным комментарием причины.'
} as const;

export const TaskStatusCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 32,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'TaskStatusCreate'
} as const;

export const TaskStatusPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 32,
            title: 'Name'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'TaskStatusPublic'
} as const;

export const TaskStatusUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 32,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'TaskStatusUpdate'
} as const;

export const TaskStatusesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TaskStatusPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TaskStatusesPublic'
} as const;

export const TaskTypeCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        execution_time: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Execution Time'
        },
        min_grade_id: {
            type: 'integer',
            title: 'Min Grade Id'
        },
        priority_id: {
            type: 'integer',
            title: 'Priority Id'
        }
    },
    type: 'object',
    required: ['name', 'execution_time', 'min_grade_id', 'priority_id'],
    title: 'TaskTypeCreate'
} as const;

export const TaskTypePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        execution_time: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Execution Time'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        min_grade_id: {
            type: 'integer',
            title: 'Min Grade Id'
        },
        priority_id: {
            type: 'integer',
            title: 'Priority Id'
        }
    },
    type: 'object',
    required: ['name', 'execution_time', 'id', 'min_grade_id', 'priority_id'],
    title: 'TaskTypePublic'
} as const;

export const TaskTypeUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        execution_time: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Execution Time'
        },
        min_grade_id: {
            type: 'integer',
            title: 'Min Grade Id'
        },
        priority_id: {
            type: 'integer',
            title: 'Priority Id'
        }
    },
    type: 'object',
    required: ['name', 'execution_time', 'min_grade_id', 'priority_id'],
    title: 'TaskTypeUpdate'
} as const;

export const TaskTypesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TaskTypePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TaskTypesPublic'
} as const;

export const TaskUpdateSchema = {
    properties: {
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        finish_time: {
            type: 'string',
            format: 'date-time',
            title: 'Finish Time'
        },
        comment: {
            type: 'string',
            maxLength: 4096,
            title: 'Comment'
        },
        employee_id: {
            type: 'integer',
            title: 'Employee Id'
        },
        task_type_id: {
            type: 'integer',
            title: 'Task Type Id'
        },
        agent_point_id: {
            type: 'integer',
            title: 'Agent Point Id'
        },
        task_status_id: {
            type: 'integer',
            title: 'Task Status Id'
        }
    },
    type: 'object',
    required: ['start_time', 'finish_time', 'comment', 'employee_id', 'task_type_id', 'agent_point_id', 'task_status_id'],
    title: 'TaskUpdate'
} as const;

export const TasksMePublicSchema = {
    properties: {
        tasks: {
            items: {
                '$ref': '#/components/schemas/TaskMePublic'
            },
            type: 'array',
            title: 'Tasks'
        },
        route: {
            anyOf: [
                {
                    items: {
                        items: {
                            type: 'number'
                        },
                        type: 'array'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Route'
        },
        start_location: {
            '$ref': '#/components/schemas/LocationPublic'
        }
    },
    type: 'object',
    required: ['tasks', 'start_location'],
    title: 'TasksMePublic'
} as const;

export const TasksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TaskPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TasksPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserCreateSchema = {
    properties: {
        login: {
            type: 'string',
            maxLength: 32,
            minLength: 3,
            title: 'Login'
        },
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name'
        },
        surname: {
            type: 'string',
            maxLength: 64,
            title: 'Surname'
        },
        middle_name: {
            type: 'string',
            maxLength: 64,
            title: 'Middle Name'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Password'
        },
        role_id: {
            type: 'integer',
            title: 'Role Id'
        }
    },
    type: 'object',
    required: ['login', 'name', 'surname', 'middle_name', 'password', 'role_id'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        login: {
            type: 'string',
            maxLength: 32,
            minLength: 3,
            title: 'Login'
        },
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name'
        },
        surname: {
            type: 'string',
            maxLength: 64,
            title: 'Surname'
        },
        middle_name: {
            type: 'string',
            maxLength: 64,
            title: 'Middle Name'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        role: {
            '$ref': '#/components/schemas/RolePublic'
        }
    },
    type: 'object',
    required: ['login', 'name', 'surname', 'middle_name', 'id', 'role'],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        login: {
            type: 'string',
            maxLength: 32,
            minLength: 3,
            title: 'Login'
        },
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name'
        },
        surname: {
            type: 'string',
            maxLength: 64,
            title: 'Surname'
        },
        middle_name: {
            type: 'string',
            maxLength: 64,
            title: 'Middle Name'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        role_id: {
            type: 'integer',
            title: 'Role Id'
        }
    },
    type: 'object',
    required: ['login', 'name', 'surname', 'middle_name', 'role_id'],
    title: 'UserUpdate'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;