// This file is auto-generated by @hey-api/openapi-ts

export type AgentPointCreate = {
    created_time?: (string | null);
    location_id: number;
};

export type AgentPointEventCreate = {
    event_time: string;
    event_type: string;
    metric_name?: (string | null);
    metric_delta?: (number | null);
    metric_value_num?: (number | null);
    metric_value_bool?: (boolean | null);
    agent_point_id: number;
};

export type AgentPointEventPublic = {
    event_time: string;
    event_type: string;
    metric_name?: (string | null);
    metric_delta?: (number | null);
    metric_value_num?: (number | null);
    metric_value_bool?: (boolean | null);
    id: number;
    agent_point_id: number;
};

export type AgentPointEventsPublic = {
    data: Array<AgentPointEventPublic>;
    count: number;
};

export type AgentPointEventUpdate = {
    event_time: string;
    event_type: string;
    metric_name?: (string | null);
    metric_delta?: (number | null);
    metric_value_num?: (number | null);
    metric_value_bool?: (boolean | null);
    agent_point_id: number;
};

export type AgentPointPublic = {
    created_time?: (string | null);
    id: number;
    location: LocationPublic;
};

export type AgentPointsPublic = {
    data: Array<AgentPointPublic>;
    count: number;
};

export type AgentPointUpdate = {
    created_time?: (string | null);
    location_id: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type EmployeeCreate = {
    user_id: number;
    grade_id: number;
    start_location_id: number;
};

export type EmployeePublic = {
    id: number;
    user_id: number;
    grade_id: number;
    start_location_id: number;
};

export type EmployeesPublic = {
    data: Array<EmployeePublic>;
    count: number;
};

export type EmployeeUpdate = {
    user_id: number;
    grade_id: number;
    start_location_id: number;
};

export type GradeCreate = {
    name: string;
    level: number;
};

export type GradePublic = {
    name: string;
    level: number;
    id: number;
};

export type GradesPublic = {
    data: Array<GradePublic>;
    count: number;
};

export type GradeUpdate = {
    name: string;
    level: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LocationCreate = {
    address: string;
    lat?: (number | null);
    lon?: (number | null);
};

export type LocationPublic = {
    address: string;
    lat?: (number | null);
    lon?: (number | null);
    id: number;
};

export type LocationsPublic = {
    data: Array<LocationPublic>;
    count: number;
};

export type LocationUpdate = {
    address: string;
    lat?: (number | null);
    lon?: (number | null);
};

export type Message = {
    message: string;
};

export type PrioritiesPublic = {
    data: Array<PriorityPublic>;
    count: number;
};

export type PriorityCreate = {
    name: string;
    level: number;
};

export type PriorityPublic = {
    name: string;
    level: number;
    id: number;
};

export type PriorityUpdate = {
    name: string;
    level: number;
};

export type RoleCreate = {
    name: string;
};

export type RolePublic = {
    name: string;
    id: number;
};

export type RolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type RoleUpdate = {
    name: string;
};

/**
 * Решение менеджера агентской точки по выполненной задаче.
 */
export type TaskAgentPointManagerConfirmUpdate = {
    confirmed: boolean;
    comment?: (string | null);
};

/**
 * Отметка задачи как выполненной с опциональным комментарием.
 */
export type TaskCompleteUpdate = {
    comment?: (string | null);
};

export type TaskCreate = {
    start_time: string;
    finish_time: string;
    comment: string;
    employee_id: number;
    task_type_id: number;
    agent_point_id: number;
    task_status_id: number;
};

export type TaskMePublic = {
    start_time: string;
    finish_time: string;
    comment: string;
    id: number;
    agent_point: AgentPointPublic;
};

export type TaskPublic = {
    start_time: string;
    finish_time: string;
    comment: string;
    id: number;
    employee_id: number;
    task_type_id: number;
    agent_point_id: number;
    task_status_id: number;
};

/**
 * Обновление статуса и комментария выездным сотрудником к своей задаче.
 */
export type TaskSelfUpdate = {
    task_status_id: number;
    comment?: (string | null);
};

/**
 * Пропуск задачи с обязательным комментарием причины.
 */
export type TaskSkipUpdate = {
    comment: string;
};

export type TasksMePublic = {
    tasks: Array<TaskMePublic>;
    route?: (Array<Array<(number)>> | null);
    start_location: LocationPublic;
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskStatusCreate = {
    name: string;
};

export type TaskStatusesPublic = {
    data: Array<TaskStatusPublic>;
    count: number;
};

export type TaskStatusPublic = {
    name: string;
    id: number;
};

export type TaskStatusUpdate = {
    name: string;
};

export type TaskTypeCreate = {
    name: string;
    execution_time: number;
    min_grade_id: number;
    priority_id: number;
};

export type TaskTypePublic = {
    name: string;
    execution_time: number;
    id: number;
    min_grade_id: number;
    priority_id: number;
};

export type TaskTypesPublic = {
    data: Array<TaskTypePublic>;
    count: number;
};

export type TaskTypeUpdate = {
    name: string;
    execution_time: number;
    min_grade_id: number;
    priority_id: number;
};

export type TaskUpdate = {
    start_time: string;
    finish_time: string;
    comment: string;
    employee_id: number;
    task_type_id: number;
    agent_point_id: number;
    task_status_id: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserCreate = {
    login: string;
    name: string;
    surname: string;
    middle_name: string;
    is_superuser?: boolean;
    password: string;
    role_id: number;
};

export type UserPublic = {
    login: string;
    name: string;
    surname: string;
    middle_name: string;
    is_superuser?: boolean;
    id: number;
    role: RolePublic;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    login: string;
    name: string;
    surname: string;
    middle_name: string;
    is_superuser?: boolean;
    password?: (string | null);
    role_id: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AgentPointEventsCreateAgentPointEventData = {
    requestBody: AgentPointEventCreate;
};

export type AgentPointEventsCreateAgentPointEventResponse = (AgentPointEventPublic);

export type AgentPointEventsReadAgentPointEventsData = {
    limit?: number;
    skip?: number;
};

export type AgentPointEventsReadAgentPointEventsResponse = (AgentPointEventsPublic);

export type AgentPointEventsReadAgentPointEventByIdData = {
    agentPointEventId: number;
};

export type AgentPointEventsReadAgentPointEventByIdResponse = (AgentPointEventPublic);

export type AgentPointEventsDeleteAgentPointEventData = {
    agentPointEventId: number;
};

export type AgentPointEventsDeleteAgentPointEventResponse = (Message);

export type AgentPointEventsUpdateAgentPointEventData = {
    id: number;
    requestBody: AgentPointEventUpdate;
};

export type AgentPointEventsUpdateAgentPointEventResponse = (AgentPointEventPublic);

export type AgentPointsCreateAgentPointData = {
    requestBody: AgentPointCreate;
};

export type AgentPointsCreateAgentPointResponse = (AgentPointPublic);

export type AgentPointsReadAgentPointsData = {
    limit?: number;
    skip?: number;
};

export type AgentPointsReadAgentPointsResponse = (AgentPointsPublic);

export type AgentPointsReadAgentPointByIdData = {
    id: number;
};

export type AgentPointsReadAgentPointByIdResponse = (AgentPointPublic);

export type AgentPointsUpdateAgentPointData = {
    id: number;
    requestBody: AgentPointUpdate;
};

export type AgentPointsUpdateAgentPointResponse = (AgentPointPublic);

export type AgentPointsDeleteAgentPointData = {
    agentPointId: number;
};

export type AgentPointsDeleteAgentPointResponse = (Message);

export type EmployeesCreateEmployeeData = {
    requestBody: EmployeeCreate;
};

export type EmployeesCreateEmployeeResponse = (EmployeePublic);

export type EmployeesReadEmployeesData = {
    limit?: number;
    skip?: number;
};

export type EmployeesReadEmployeesResponse = (EmployeesPublic);

export type EmployeesReadEmployeeByIdData = {
    employeeId: number;
};

export type EmployeesReadEmployeeByIdResponse = (EmployeePublic);

export type EmployeesDeleteEmployeeData = {
    employeeId: number;
};

export type EmployeesDeleteEmployeeResponse = (Message);

export type EmployeesUpdateEmployeeData = {
    id: number;
    requestBody: EmployeeUpdate;
};

export type EmployeesUpdateEmployeeResponse = (EmployeePublic);

export type GradesCreateGradeData = {
    requestBody: GradeCreate;
};

export type GradesCreateGradeResponse = (GradePublic);

export type GradesReadGradesData = {
    limit?: number;
    skip?: number;
};

export type GradesReadGradesResponse = (GradesPublic);

export type GradesReadGradeByIdData = {
    gradeId: number;
};

export type GradesReadGradeByIdResponse = (GradePublic);

export type GradesDeleteGradeData = {
    gradeId: number;
};

export type GradesDeleteGradeResponse = (Message);

export type GradesUpdateGradeData = {
    id: number;
    requestBody: GradeUpdate;
};

export type GradesUpdateGradeResponse = (GradePublic);

export type LocationsCreateLocationData = {
    requestBody: LocationCreate;
};

export type LocationsCreateLocationResponse = (LocationPublic);

export type LocationsReadLocationsData = {
    limit?: number;
    skip?: number;
};

export type LocationsReadLocationsResponse = (LocationsPublic);

export type LocationsReadLocationByIdData = {
    locationId: number;
};

export type LocationsReadLocationByIdResponse = (LocationPublic);

export type LocationsDeleteLocationData = {
    locationId: number;
};

export type LocationsDeleteLocationResponse = (Message);

export type LocationsUpdateLocationData = {
    id: number;
    requestBody: LocationUpdate;
};

export type LocationsUpdateLocationResponse = (LocationPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type PrioritiesCreatePriorityData = {
    requestBody: PriorityCreate;
};

export type PrioritiesCreatePriorityResponse = (PriorityPublic);

export type PrioritiesReadPrioritiesData = {
    limit?: number;
    skip?: number;
};

export type PrioritiesReadPrioritiesResponse = (PrioritiesPublic);

export type PrioritiesReadPriorityByIdData = {
    priorityId: number;
};

export type PrioritiesReadPriorityByIdResponse = (PriorityPublic);

export type PrioritiesDeletePriorityData = {
    priorityId: number;
};

export type PrioritiesDeletePriorityResponse = (Message);

export type PrioritiesUpdatePriorityData = {
    id: number;
    requestBody: PriorityUpdate;
};

export type PrioritiesUpdatePriorityResponse = (PriorityPublic);

export type RolesCreateRoleData = {
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (RolePublic);

export type RolesReadRolesData = {
    limit?: number;
    skip?: number;
};

export type RolesReadRolesResponse = (RolesPublic);

export type RolesReadRoleByIdData = {
    roleId: number;
};

export type RolesReadRoleByIdResponse = (RolePublic);

export type RolesDeleteRoleData = {
    roleId: number;
};

export type RolesDeleteRoleResponse = (Message);

export type RolesUpdateRoleData = {
    id: number;
    requestBody: RoleUpdate;
};

export type RolesUpdateRoleResponse = (RolePublic);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksReadTasksData = {
    limit?: number;
    skip?: number;
};

export type TasksReadTasksResponse = (TasksPublic);

export type TasksDistributeTasksResponse = (Message);

export type TasksReadTasksMeData = {
    limit?: number;
    skip?: number;
};

export type TasksReadTasksMeResponse = (TasksMePublic);

export type TasksUpdateMyTaskStatusData = {
    requestBody: TaskSelfUpdate;
    taskId: number;
};

export type TasksUpdateMyTaskStatusResponse = (TaskPublic);

export type TasksCompleteMyTaskData = {
    requestBody: TaskCompleteUpdate;
    taskId: number;
};

export type TasksCompleteMyTaskResponse = (TaskPublic);

export type TasksSkipMyTaskData = {
    requestBody: TaskSkipUpdate;
    taskId: number;
};

export type TasksSkipMyTaskResponse = (TaskPublic);

export type TasksCompleteTaskByAgentPointManagerData = {
    requestBody: TaskAgentPointManagerConfirmUpdate;
    taskId: number;
};

export type TasksCompleteTaskByAgentPointManagerResponse = (TaskPublic);

export type TasksReadTaskByIdData = {
    taskId: number;
};

export type TasksReadTaskByIdResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    taskId: number;
};

export type TasksDeleteTaskResponse = (Message);

export type TasksUpdateTaskData = {
    id: number;
    requestBody: TaskUpdate;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TaskStatusesCreateTaskStatusData = {
    requestBody: TaskStatusCreate;
};

export type TaskStatusesCreateTaskStatusResponse = (TaskStatusPublic);

export type TaskStatusesReadTaskStatusesData = {
    limit?: number;
    skip?: number;
};

export type TaskStatusesReadTaskStatusesResponse = (TaskStatusesPublic);

export type TaskStatusesReadTaskStatusByIdData = {
    taskStatusId: number;
};

export type TaskStatusesReadTaskStatusByIdResponse = (TaskStatusPublic);

export type TaskStatusesDeleteTaskStatusData = {
    taskStatusId: number;
};

export type TaskStatusesDeleteTaskStatusResponse = (Message);

export type TaskStatusesUpdateTaskStatusData = {
    id: number;
    requestBody: TaskStatusUpdate;
};

export type TaskStatusesUpdateTaskStatusResponse = (TaskStatusPublic);

export type TaskTypesCreateTaskTypeData = {
    requestBody: TaskTypeCreate;
};

export type TaskTypesCreateTaskTypeResponse = (TaskTypePublic);

export type TaskTypesReadTaskTypesData = {
    limit?: number;
    skip?: number;
};

export type TaskTypesReadTaskTypesResponse = (TaskTypesPublic);

export type TaskTypesReadTaskTypeByIdData = {
    taskTypeId: number;
};

export type TaskTypesReadTaskTypeByIdResponse = (TaskTypePublic);

export type TaskTypesDeleteTaskTypeData = {
    taskTypeId: number;
};

export type TaskTypesDeleteTaskTypeResponse = (Message);

export type TaskTypesUpdateTaskTypeData = {
    id: number;
    requestBody: TaskTypeUpdate;
};

export type TaskTypesUpdateTaskTypeResponse = (TaskTypePublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: number;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: number;
};

export type UsersDeleteUserResponse = (Message);

export type UsersUpdateUserData = {
    id: number;
    requestBody: UserUpdate;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UtilsHealthCheckResponse = (boolean);