// This file is auto-generated by @hey-api/openapi-ts

export type AgentPointPublic = {
  created_time: string;
  is_cards_delivered: boolean;
  days_since_last_card_gived: number;
  approved_applications: number;
  cards_gived: number;
  id: number;
  location: LocationPublic;
};

export type AgentPointsPublic = {
  data: Array<AgentPointPublic>;
  count: number;
};

export type Body_login_login_access_token = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type EmployeePublic = {
  id: number;
  user_id: number;
  grade_id: number;
  start_location_id: number;
};

export type EmployeesPublic = {
  data: Array<EmployeePublic>;
  count: number;
};

export type GradePublic = {
  name: string;
  level: number;
  id: number;
};

export type GradesPublic = {
  data: Array<GradePublic>;
  count: number;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type LocationPublic = {
  address: string;
  lat?: number | null;
  lon?: number | null;
  id: number;
};

export type LocationsPublic = {
  data: Array<LocationPublic>;
  count: number;
};

export type Message = {
  message: string;
};

export type PrioritiesPublic = {
  data: Array<PriorityPublic>;
  count: number;
};

export type PriorityPublic = {
  name: string;
  level: number;
  id: number;
};

export type RolePublic = {
  name: string;
  id: number;
};

export type RolesPublic = {
  data: Array<RolePublic>;
  count: number;
};

export type TaskMePublic = {
  start_time: string;
  finish_time: string;
  comment: string;
  id: number;
  agent_point: AgentPointPublic;
};

export type TaskPublic = {
  start_time: string;
  finish_time: string;
  comment: string;
  id: number;
  employee_id: number;
  task_type_id: number;
  agent_point_id: number;
  task_status_id: number;
};

export type TasksMePublic = {
  tasks: Array<TaskMePublic>;
  route: string | null;
  start_location: LocationPublic;
};

export type TasksPublic = {
  data: Array<TaskPublic>;
  count: number;
};

export type TaskStatusesPublic = {
  data: Array<TaskStatusPublic>;
  count: number;
};

export type TaskStatusPublic = {
  name: string;
  id: number;
};

export type TaskTypePublic = {
  name: string;
  execution_time: number;
  id: number;
  min_grade_id: number;
  priority_id: number;
};

export type TaskTypesPublic = {
  data: Array<TaskTypePublic>;
  count: number;
};

export type Token = {
  access_token: string;
  token_type?: string;
};

export type UserCreate = {
  login: string;
  name: string;
  surname: string;
  middle_name: string;
  is_superuser?: boolean;
  password: string;
  role_id: number;
};

export type UserPublic = {
  login: string;
  name: string;
  surname: string;
  middle_name: string;
  is_superuser?: boolean;
  id: number;
  role: string;
};

export type UsersPublic = {
  data: Array<UserPublic>;
  count: number;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AgentPointsReadAgentPointsData = {
  limit?: number;
  skip?: number;
};

export type AgentPointsReadAgentPointsResponse = AgentPointsPublic;

export type AgentPointsReadAgentPointByIdData = {
  agentPointId: number;
};

export type AgentPointsReadAgentPointByIdResponse = AgentPointPublic;

export type AgentPointsDeleteAgentPointData = {
  agentPointId: number;
};

export type AgentPointsDeleteAgentPointResponse = Message;

export type EmployeesReadEmployeesData = {
  limit?: number;
  skip?: number;
};

export type EmployeesReadEmployeesResponse = EmployeesPublic;

export type EmployeesReadEmployeeByIdData = {
  employeeId: number;
};

export type EmployeesReadEmployeeByIdResponse = EmployeePublic;

export type EmployeesDeleteEmployeeData = {
  employeeId: number;
};

export type EmployeesDeleteEmployeeResponse = Message;

export type GradesReadGradesData = {
  limit?: number;
  skip?: number;
};

export type GradesReadGradesResponse = GradesPublic;

export type GradesReadGradeByIdData = {
  gradeId: number;
};

export type GradesReadGradeByIdResponse = GradePublic;

export type GradesDeleteGradeData = {
  gradeId: number;
};

export type GradesDeleteGradeResponse = Message;

export type LocationsReadLocationsData = {
  limit?: number;
  skip?: number;
};

export type LocationsReadLocationsResponse = LocationsPublic;

export type LocationsReadLocationByIdData = {
  locationId: number;
};

export type LocationsReadLocationByIdResponse = LocationPublic;

export type LocationsDeleteLocationData = {
  locationId: number;
};

export type LocationsDeleteLocationResponse = Message;

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = Token;

export type LoginTestTokenResponse = UserPublic;

export type PrioritiesReadPrioritiesData = {
  limit?: number;
  skip?: number;
};

export type PrioritiesReadPrioritiesResponse = PrioritiesPublic;

export type PrioritiesReadPriorityByIdData = {
  priorityId: number;
};

export type PrioritiesReadPriorityByIdResponse = PriorityPublic;

export type PrioritiesDeletePriorityData = {
  priorityId: number;
};

export type PrioritiesDeletePriorityResponse = Message;

export type RolesReadRolesData = {
  limit?: number;
  skip?: number;
};

export type RolesReadRolesResponse = RolesPublic;

export type RolesReadRoleByIdData = {
  roleId: number;
};

export type RolesReadRoleByIdResponse = RolePublic;

export type RolesDeleteRoleData = {
  roleId: number;
};

export type RolesDeleteRoleResponse = Message;

export type TasksReadTasksData = {
  limit?: number;
  skip?: number;
};

export type TasksReadTasksResponse = TasksPublic;

export type TasksReadTasksMeData = {
  limit?: number;
  skip?: number;
};

export type TasksReadTasksMeResponse = TasksMePublic;

export type TasksReadTaskByIdData = {
  taskId: number;
};

export type TasksReadTaskByIdResponse = TaskPublic;

export type TasksDeleteTaskData = {
  taskId: number;
};

export type TasksDeleteTaskResponse = Message;

export type TaskStatusesReadTaskStatusesData = {
  limit?: number;
  skip?: number;
};

export type TaskStatusesReadTaskStatusesResponse = TaskStatusesPublic;

export type TaskStatusesReadTaskStatusByIdData = {
  taskStatusId: number;
};

export type TaskStatusesReadTaskStatusByIdResponse = TaskStatusPublic;

export type TaskStatusesDeleteTaskStatusData = {
  taskStatusId: number;
};

export type TaskStatusesDeleteTaskStatusResponse = Message;

export type TaskTypesReadTaskTypesData = {
  limit?: number;
  skip?: number;
};

export type TaskTypesReadTaskTypesResponse = TaskTypesPublic;

export type TaskTypesReadTaskTypeByIdData = {
  taskTypeId: number;
};

export type TaskTypesReadTaskTypeByIdResponse = TaskTypePublic;

export type TaskTypesDeleteTaskTypeData = {
  taskTypeId: number;
};

export type TaskTypesDeleteTaskTypeResponse = Message;

export type UsersReadUsersData = {
  limit?: number;
  skip?: number;
};

export type UsersReadUsersResponse = UsersPublic;

export type UsersCreateUserData = {
  requestBody: UserCreate;
};

export type UsersCreateUserResponse = UserPublic;

export type UsersReadUserMeResponse = UserPublic;

export type UsersReadUserByIdData = {
  userId: number;
};

export type UsersReadUserByIdResponse = UserPublic;

export type UsersDeleteUserData = {
  userId: number;
};

export type UsersDeleteUserResponse = Message;

export type UtilsHealthCheckResponse = boolean;
