/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTasksRouteImport } from './routes/_layout/tasks'
import { Route as LayoutTaskTypesRouteImport } from './routes/_layout/task-types'
import { Route as LayoutTaskStatusesRouteImport } from './routes/_layout/task-statuses'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRolesRouteImport } from './routes/_layout/roles'
import { Route as LayoutPrioritiesRouteImport } from './routes/_layout/priorities'
import { Route as LayoutLocationsRouteImport } from './routes/_layout/locations'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutGradesRouteImport } from './routes/_layout/grades'
import { Route as LayoutEmployeesRouteImport } from './routes/_layout/employees'
import { Route as LayoutAgentPointsRouteImport } from './routes/_layout/agent-points'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaskTypesRoute = LayoutTaskTypesRouteImport.update({
  id: '/task-types',
  path: '/task-types',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaskStatusesRoute = LayoutTaskStatusesRouteImport.update({
  id: '/task-statuses',
  path: '/task-statuses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRolesRoute = LayoutRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrioritiesRoute = LayoutPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLocationsRoute = LayoutLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGradesRoute = LayoutGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmployeesRoute = LayoutEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentPointsRoute = LayoutAgentPointsRouteImport.update({
  id: '/agent-points',
  path: '/agent-points',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agent-points': typeof LayoutAgentPointsRoute
  '/employees': typeof LayoutEmployeesRoute
  '/grades': typeof LayoutGradesRoute
  '/items': typeof LayoutItemsRoute
  '/locations': typeof LayoutLocationsRoute
  '/priorities': typeof LayoutPrioritiesRoute
  '/roles': typeof LayoutRolesRoute
  '/settings': typeof LayoutSettingsRoute
  '/task-statuses': typeof LayoutTaskStatusesRoute
  '/task-types': typeof LayoutTaskTypesRoute
  '/tasks': typeof LayoutTasksRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agent-points': typeof LayoutAgentPointsRoute
  '/employees': typeof LayoutEmployeesRoute
  '/grades': typeof LayoutGradesRoute
  '/items': typeof LayoutItemsRoute
  '/locations': typeof LayoutLocationsRoute
  '/priorities': typeof LayoutPrioritiesRoute
  '/roles': typeof LayoutRolesRoute
  '/settings': typeof LayoutSettingsRoute
  '/task-statuses': typeof LayoutTaskStatusesRoute
  '/task-types': typeof LayoutTaskTypesRoute
  '/tasks': typeof LayoutTasksRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/agent-points': typeof LayoutAgentPointsRoute
  '/_layout/employees': typeof LayoutEmployeesRoute
  '/_layout/grades': typeof LayoutGradesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/locations': typeof LayoutLocationsRoute
  '/_layout/priorities': typeof LayoutPrioritiesRoute
  '/_layout/roles': typeof LayoutRolesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/task-statuses': typeof LayoutTaskStatusesRoute
  '/_layout/task-types': typeof LayoutTaskTypesRoute
  '/_layout/tasks': typeof LayoutTasksRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agent-points'
    | '/employees'
    | '/grades'
    | '/items'
    | '/locations'
    | '/priorities'
    | '/roles'
    | '/settings'
    | '/task-statuses'
    | '/task-types'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agent-points'
    | '/employees'
    | '/grades'
    | '/items'
    | '/locations'
    | '/priorities'
    | '/roles'
    | '/settings'
    | '/task-statuses'
    | '/task-types'
    | '/tasks'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/agent-points'
    | '/_layout/employees'
    | '/_layout/grades'
    | '/_layout/items'
    | '/_layout/locations'
    | '/_layout/priorities'
    | '/_layout/roles'
    | '/_layout/settings'
    | '/_layout/task-statuses'
    | '/_layout/task-types'
    | '/_layout/tasks'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/task-types': {
      id: '/_layout/task-types'
      path: '/task-types'
      fullPath: '/task-types'
      preLoaderRoute: typeof LayoutTaskTypesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/task-statuses': {
      id: '/_layout/task-statuses'
      path: '/task-statuses'
      fullPath: '/task-statuses'
      preLoaderRoute: typeof LayoutTaskStatusesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/roles': {
      id: '/_layout/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof LayoutRolesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/priorities': {
      id: '/_layout/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof LayoutPrioritiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/locations': {
      id: '/_layout/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LayoutLocationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/grades': {
      id: '/_layout/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof LayoutGradesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/employees': {
      id: '/_layout/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof LayoutEmployeesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agent-points': {
      id: '/_layout/agent-points'
      path: '/agent-points'
      fullPath: '/agent-points'
      preLoaderRoute: typeof LayoutAgentPointsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAgentPointsRoute: typeof LayoutAgentPointsRoute
  LayoutEmployeesRoute: typeof LayoutEmployeesRoute
  LayoutGradesRoute: typeof LayoutGradesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutLocationsRoute: typeof LayoutLocationsRoute
  LayoutPrioritiesRoute: typeof LayoutPrioritiesRoute
  LayoutRolesRoute: typeof LayoutRolesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTaskStatusesRoute: typeof LayoutTaskStatusesRoute
  LayoutTaskTypesRoute: typeof LayoutTaskTypesRoute
  LayoutTasksRoute: typeof LayoutTasksRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAgentPointsRoute: LayoutAgentPointsRoute,
  LayoutEmployeesRoute: LayoutEmployeesRoute,
  LayoutGradesRoute: LayoutGradesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutLocationsRoute: LayoutLocationsRoute,
  LayoutPrioritiesRoute: LayoutPrioritiesRoute,
  LayoutRolesRoute: LayoutRolesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTaskStatusesRoute: LayoutTaskStatusesRoute,
  LayoutTaskTypesRoute: LayoutTaskTypesRoute,
  LayoutTasksRoute: LayoutTasksRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
